id = "rescript"
name = "ReScript"
description = "ReScript support."
version = "0.5.1"
schema_version = 1
authors = ["Karolis Narkevicius <hey@kn8.lt>"]
repository = "https://github.com/sigurthor/rescript-zed"

[language_servers.rescript-language-server]
name = "rescript-language-server"
language = "ReScript"

[grammars.rescript]
repository = "https://github.com/sigurthor/tree-sitter-rescript"
commit = "4737140db25c16fb3ed4a13c4a972ee6535b7fa7"
